events {}

http {

  log_format traffic '$hostname | $remote_addr | $http_user_agent | ROUTER-> $upstream_addr';

  map $http_user_agent $is_bot {
    default 0;
    "~*bot" 1;
  }

  upstream tracker_backend {
    server tracker:80;
  }

  upstream backup_backend {
    server safe-landing:80;
  }

  server {
    listen 80;
    access_log /var/log/nginx/router_access.log traffic;

    location / {

      if ($is_bot = 1) {
        proxy_pass http://backup_backend;
        break;
      }

      proxy_pass http://tracker_backend;
    }
  }
}
